### ISSUE TITLE
[bug] `zsh` recognize `backspace` as `blankspace`

### ISSUE THREAD

**Issue by TTTPOB** [romkatv/zsh-bin#12]
https://user-images.githubusercontent.com/19909103/198538760-6098b068-464a-4dc5-8012-6d1b24a823de.mp4

after I typed these letters, they only keys I pressed were `backspace`s

system information:
```
OS: CentOS Linux 7 (Core) x86_64
Kernel: 3.10.0-1062.9.1.el7.x86_64


$ echo $TERM
> xterm-256color
```

**Comment by romkatv** [comment]
The video isn't playing for me. In the future please report bugs with plain text.

zsh-bin doesn't change anything in zsh w.r.t. the handling of keys. You can bind keys the same way as you would do in zsh everywhere.

**Comment by TTTPOB** [comment]
I think this may not be a key-binding issue.
`ctrl + v` followed by `backspace` produces `^^@`, which is the ASCII representation of `space`
`ctrl + v` followed by `ctrl + H` produces `^^@` as well.
`bindkeys ^H` give me the expected `"^H" backward-delete-char`

 So I think maybe there are some problems with the treatment of key event? Can this be related to `terminfo`?

**Comment by romkatv** [comment]
Terminfo doesn't affect the byte sequences sent by the terminal when you press keys.

Do you have any reason to believe that you've opened this issue against a relevant component?

**Comment by TTTPOB** [comment]
No, I don't.
I have listed all the information I have and all things I've tried.
The only reason I posted an issue here is that `zsh` from system package manager and the one I compiled from source worked fine, and I think you might have some clue on this behavior.
So you think I should get help elsewhere and close this issue?

**Comment by romkatv** [comment]
> The only reason I posted an issue here is that `zsh` from system package manager and the one I compiled from source worked fine, and I think you might have some clue on this behavior.

This changes things. Can you double check this?

1. Start `zsh` from the system package manager.
2. Verify that backspace generates `^?` (decimal 127).
3. Without exiting the current shell start `zsh` from zsh-bin.
4. Verify that backspace generates `^^@` (decimal 30 followed by decimal 64).
5. Without exiting the current shell start `zsh` from the system package manager.
6. Verify that backspace generates `^?` (decimal 127).

If you can confirm all of this, please attach the output of `infocmp` executed from the system package manager's `zsh` and from zsh-bin's `zsh`.

FWIW, I cannot reproduce this in docker.

```text
% docker run -e TERM -it --rm centos:centos7 bash
[root@096a1523fcbe /]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
[root@096a1523fcbe /]# sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh-bin/master/install)"
Choose installation directory for Zsh 5.8:

  (1)  /usr/local        <= does not need sudo (recommended)
  (2)  ~/.local          <= does not need sudo
  (3)  Custom directory.
  (q)  Quit and do nothing.

Choice [123q]: 1

===> installing Zsh 5.8 to /usr/local
===> fetching zsh-5.8-linux-x86_64.tar.gz
===> verifying archive integrity
===> sha256 signature matches
===> md5 signature matches
===> extracting files

Add /usr/local/bin/zsh to /etc/shells?

This will allow you to use it as a login shell.

  (y)  Yes. Recommended.
  (n)  No.
  (q)  Quit and do nothing.

Choice [ynq]: y

===> adding /usr/local/bin/zsh to /etc/shells

Installed Zsh 5.8 to /usr/local

To start Zsh, type:

  zsh

[root@096a1523fcbe /]# zsh
096a1523fcbe# typeset -p TERM
export TERM=xterm-256color
096a1523fcbe# ^?
```

On the last line I've pressed <kbd>Ctrl-V</kbd> followed by `Backspace` (I'm using a PC keyboard). The output is `^?`, as expected.
