### ISSUE TITLE
how to install zsh without internet

### ISSUE THREAD

**Issue by songzenghui** [romkatv/zsh-bin#15]
I can download zsh.tar, and upload these to my linux which has not internet

**Comment by romkatv** [comment]
Download the appropriate archive and run the installer with `-f`. The installer has `-h` for help.

**Comment by NewtonChutney** [comment]
> Download the appropriate archive and run the installer with `-f`. The installer has `-h` for help.

Could you change the Readme to reflect that this option exists? Preferably near the manual installation section! 
I had spent a lot of time manually untaring the files but with zsh not picking the functions under ~/.local/share... 😢

Thanks!

**Comment by romkatv** [comment]
I added a short paragraph to the docs that mentions `install -f`: https://github.com/romkatv/zsh-bin/commit/6e856abb802a6400298605483be94cc5e2310f3f

**Comment by NewtonChutney** [comment]
Thanks a ton! ♥ 
This issue can be closed?
