### ISSUE TITLE
zsh history is not saved: locking failed for ...history: no such file or directory

### ISSUE THREAD

**Issue by papanito** [romkatv/zsh-bin#16]
I start `zsh` within a git-bash on Windows, it works fine so far except that history is not saved

```
# History
export HISTFILE="$HOME/.cache/zsh/history"
export HISTSIZE=2000
export SAVEHIST=1000
setopt bang_hist                # Treat The '!' Character Specially During Expansion.
setopt inc_append_history       # Write To The History File Immediately, Not When The Shell Exits.
setopt share_history            # Share History Between All Sessions.
setopt hist_expire_dups_first   # Expire A Duplicate Event First When Trimming History.
setopt hist_ignore_dups         # Do Not Record An Event That Was Just Recorded Again.
setopt hist_ignore_all_dups     # Delete An Old Recorded Event If A New Event Is A Duplicate.
setopt hist_find_no_dups        # Do Not Display A Previously Found Event.
setopt hist_ignore_space        # Do Not Record An Event Starting With A Space.
setopt hist_save_no_dups        # Do Not Write A Duplicate Event To The History File.
setopt hist_verify              # Do Not Execute Immediately Upon History Expansion.
setopt extended_history         # Show Timestamp In History
bindkey -e
```

Directory `$HOME/.cache/zsh` exists, but when I close zsh I get the following error

```
zsh: locking failed for /c/Users/papanito/.cache/zsh/history: no such file or directory
```

**Comment by romkatv** [comment]
> ```
> # History
> export HISTFILE="$HOME/.cache/zsh/history"
> export HISTSIZE=2000
> export SAVEHIST=1000
> setopt bang_hist                # Treat The '!' Character Specially During Expansion.
> setopt inc_append_history       # Write To The History File Immediately, Not When The Shell Exits.
> setopt share_history            # Share History Between All Sessions.
> setopt hist_expire_dups_first   # Expire A Duplicate Event First When Trimming History.
> setopt hist_ignore_dups         # Do Not Record An Event That Was Just Recorded Again.
> setopt hist_ignore_all_dups     # Delete An Old Recorded Event If A New Event Is A Duplicate.
> setopt hist_find_no_dups        # Do Not Display A Previously Found Event.
> setopt hist_ignore_space        # Do Not Record An Event Starting With A Space.
> setopt hist_save_no_dups        # Do Not Write A Duplicate Event To The History File.
> setopt hist_verify              # Do Not Execute Immediately Upon History Expansion.
> setopt extended_history         # Show Timestamp In History
> bindkey -e
> ```

What happens if you remove all of this?

**Comment by romkatv** [comment]
Ah, sorry, I thought this issue was filed under zsh4humans. I don't know why you are getting this error.

**Comment by papanito** [comment]
Oh was worth a shot, maybe you knew if this is a know issue. Interestingly, if I do `history > $HISTFILE` in the session, and then open zsh in a new window, I also get the lock error but when starting.

```
locking failed for /c/Users/papanito/.cache/zsh/history: no such file or directory: reading anyway
```

**Comment by romkatv** [comment]
You could try setting or unsetting `HIST_FCNTL_LOCK`.

**Comment by papanito** [comment]
Cool that actually seems to work. Many many thanks for your support.
