### ISSUE TITLE
OSTYPE not set up 

### ISSUE THREAD

**Issue by commiyou** [romkatv/zsh-bin#3]
OSTYPE variable is determined at compile time. 
![image](https://user-images.githubusercontent.com/5888756/82650897-faa8c200-9c4d-11ea-9acc-3f92dd751b68.png)

**Comment by romkatv** [comment]
What would you expect from `zsh --version`?

**Comment by commiyou** [comment]
![image](https://user-images.githubusercontent.com/5888756/82701364-a67bfd00-9ca2-11ea-8611-4884a8553bc6.png)
`zsh --version` should display _zsh  ZSH_VERSION (MACHTYPE-VENDOR-OSTYPE)_ (You can find it in _Src/init.c_)
but the zsh-bin always outputs pc-none

**Comment by romkatv** [comment]
So, what would you expect from `zsh --version`?

**Comment by romkatv** [comment]
To clarify, I'd like to know what you expect. So far you've only posted screenshots of the current state of affairs (thanks!) but nothing about how you want it changed. Send a PR maybe?

**Comment by commiyou** [comment]
I expect `zsh -c 'echo $OSTYPE'` output right OSTYPE. The release‘s bin always output _none_
![image](https://user-images.githubusercontent.com/5888756/82725892-d9f67000-9d12-11ea-9075-8f071a9b651a.png)
![image](https://user-images.githubusercontent.com/5888756/82725941-2b066400-9d13-11ea-93b4-6b9108538a08.png)

It can be solved by change `--host` from `$ZSH_BIN_ARCH` to `$ZSH_BIN_ARCH-$ZSH_BIN_KERNEL`, or `./config.guess`.
[code](https://github.com/romkatv/zsh-bin/blob/80cf6720614d31237a3afbfb37b4e15082480c35/build#L304)

**Comment by romkatv** [comment]
Thanks for the additional clarification!

I've fixed `build` as you suggested and released v4.0.1.
