### ISSUE TITLE
[Documentation] Would it be possible to add a subsection how to comple zsh statically on your own?

### ISSUE THREAD

**Issue by rubyFeedback** [romkatv/zsh-bin#4]
Hello Roman,

First, the documentation is really fine - very detailed. I did not read everything :-), but it
is good to see a project has high quality and extensive documentation available.

Now to the issue of this request:

Currently we have this paragraph:

    sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh-bin/master/build)"

    Tip: build has a few optional flags. Invoke it with -h to list them.

    On Linux build is done in a Docker container, so you'll need to install docker first. On non-Linux 
    systems build is done on the host. In the latter case it's recommended to run the script in a freshly 
    installed OS.

    If everything goes well, zsh-5.8-${KERNEL}-${ARCH}.tar.gz will appear in the current directory

Now this is fine, but do you think a new subsection could be added, or perhaps linked in
to a separate .md file, how to "do-it-yourself"? Aka if someone wants to compile a static
variant of zsh. Being relocatable even better.

The primary reason for this issue request is the following:

- This may teach people how to get things to work. For example, I can compile a static
variant of bash, but I fail with zsh right now for reasons I don't understand. But I like
to be able to understand if possible (I compile everything from source).

If it is too much work or out of scope of the project please just feel free to close this
at any moment in time. Does not have to be a lot of documentation, a paragraph
may suffice just for people to get started.

**Comment by romkatv** [comment]
I’m not sure I understand. If you want to compile zsh, run the build script. If you want to know how it works, looks at its code.
