### ISSUE TITLE
Use bash instead of sh for install

### ISSUE THREAD

**Issue by cyrinux** [romkatv/zsh-bin#5]
Hi @romkatv ,

First thanks for z4h 👍 .

I was debugging z4h install and i discover that this fail with dash. That is the default sh of ubuntu.

```
sudo docker run --rm -it ubuntu:trusty
```

![image](https://user-images.githubusercontent.com/519083/86534778-806d8d80-bedb-11ea-96d1-3a9104a9e5f6.png)

I need to manage a lot of old ubuntu trusty and so one fix is to force using bash instead of dash with:

```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh-bin/master/install)"
```

and all others place where `sh` is call.

or maybe you will find how to make this dash and bash compliant.

Thanks !

**Comment by romkatv** [comment]
Thanks for the report.

The install script works with any POSIX-compliant `sh`. Apparently a 6-year-old version of dash is not POSIX-compliant. I've added a workaround to `install` for this particular bug and have verified that it works with dash that ships with Ubuntu Trusty.

**Comment by cyrinux** [comment]
Thanks you very much. Now we just miss "kitty ssh" replacement in z4h to don't need to kitty ssh then z4h ssh 👍  😄

**Comment by romkatv** [comment]
See https://github.com/romkatv/zsh4humans/issues/32. `z4h ssh` will automatically install zsh-bin if there is no terminfo entry for `$TERM` on the remote server. zsh-bin will have terminfo for kitty starting from the next release.

In my setup I also have this function:

```function ssh() { z4h ssh "$@" }```

When I want to use plain `ssh`, I use `command ssh`. You can also use `zstyle` to specify that `z4h ssh` should simply delegate to `ssh` for some hosts. It looks like this:

```zsh
zstyle :z4h:ssh:foo.com passthrough yes
```

(I'm referring to zsh4humans v3 here. I think it's different in v2, which you are probably using. v3 is still in development and will go public some time in the future.)

**Comment by cyrinux** [comment]
I'm using v3 with maximbaz ;), thanks for tips and ok, cool so I just wait the next release 👍

**Comment by romkatv** [comment]
> See [romkatv/zsh4humans#32](https://github.com/romkatv/zsh4humans/issues/32).

FYI: That issue has been closed.
