### ISSUE TITLE
request - update to 5.8.1

### ISSUE THREAD

**Issue by PLumowina** [romkatv/zsh-bin#7]
Hi, hello is there possibility to upgrade your build script to zsh 5.8.1 ?
i try to compile it - but when I use it i dont work as old 5.8 version (cant delete letters/words with backspace/ctrl+h/ctr+w)
dont know why is it so.

**Comment by romkatv** [comment]
> Hi, hello is there possibility to upgrade your build script to zsh 5.8.1 ?

It's technically possible but it's not in my plans right now.

May I ask why you want this? Are you affected by the bug fix from 5.8.1? Does the described workaround work for you?

**Comment by dufferzafar** [comment]
@romkatv Will you be triggering a build for 5.9?

**Comment by romkatv** [comment]
I might eventually but not soon.

**Comment by romkatv** [comment]
Closing in favor of https://github.com/romkatv/zsh-bin/issues/11
