### ISSUE TITLE
How to install on a linux machine that doesn't have internet

### ISSUE THREAD

**Issue by ayroblu** [romkatv/zsh-bin#8]
Due to restrictions I have, I was wondering what it takes to get this to work for machines without internet access? Ideally it's simply download the binary and scp it across though you've mentioned that's not the best way

**Comment by romkatv** [comment]
Download these two files:

- https://github.com/romkatv/zsh-bin/releases/download/v6.1.0/zsh-5.8-linux-x86_64.tar.gz
- https://raw.githubusercontent.com/romkatv/zsh-bin/master/install

Copy them over to the machine where you want to install zsh. Then run:

```sh
sh ./install -f zsh-5.8-linux-x86_64.tar.gz
```

**Comment by ayroblu** [comment]
Amazing, thanks!

```
curl -fLO https://github.com/romkatv/zsh-bin/releases/download/v6.1.0/zsh-5.8-linux-x86_64.tar.gz
curl -fLO https://raw.githubusercontent.com/romkatv/zsh-bin/master/install
rsync -aPvv zsh-5* install machine:
ssh machine "sh ./install -f zsh-5.8-linux-x86_64.tar.gz"
```

**Comment by simula67** [comment]
Thank you. Please consider adding a link to this in the Readme.
